### ISSUE TITLE
Adapt to meson/ninja for libvips

### ISSUE THREAD

**Issue by lovell** [lovell/sharp-libvips#127]
libvips is moving to meson as its build tool of choice, which is a welcome change, but with great power comes a little breakage.

https://github.com/libvips/libvips/pull/2637

The scripts in this repo currently take advantage of the ability to mix and match the creation of shared and static libraries with autotools, namely libvips as a static C library then the C++ wrapper as a shared library with all of its dependencies statically linked.

meson uses ninja as its build tool, which is intentionally simple, a good thing, so I think we'll need to make separate invocations of `meson` to achieve the current approach.

I owe @kleisauke far too many € already, but I'm sure he has some ideas here, and I'm opening this issue only because this is not going to be a 15 minute job.

**Comment by kleisauke** [comment]
Here's a branch that seems to build for me:
https://github.com/lovell/sharp-libvips/compare/main...kleisauke:meson

I had to apply these workarounds for Meson:
- Make libaom a non-private dependency of libheif, since Meson doesn't respect the `PKG_CONFIG="pkg-config --static"` env to force outputting linker flags for static linking.
- Use `install_rpath: '$ORIGIN/'` on the `libvips-cpp.so.42` lib target rather than `LDFLAGS='-Wl,-rpath=$ORIGIN/'`, since Meson removes relative rpaths specified in the `LDFLAGS` env during installation.

In addition, I updated GCC to version 11 and reduced the symbol table by using GNU symbol visibility and the `-Wl,--exclude-libs=` linker options (which reduced the library size by ~0.6 MB). Unfortunately, these tricks with symbol visibility did not work at runtime, I got this error:
```
node: symbol lookup error: /home/kleisauke/sharp/build/Release/sharp-linux-x64.node: undefined symbol: g_type_check_instance_is_a
```

This is probably because libvips implements several classes in its header file. For example, removing all `VIPS_IS_OBJECT` calls here:
https://github.com/libvips/libvips/blob/0d8056b8c59818e0f57c379d64db8e1ffaa00a03/cplusplus/include/vips/VImage8.h#L84-L85

Transforms the error into:
```
node: symbol lookup error: /home/kleisauke/sharp/build/Release/sharp-linux-x64.node: undefined symbol: g_object_ref
```

Maybe I shouldn't hide all symbols of `libgobject-2.0.a`, but just `g_param_spec_types`. I'll look into this further tomorrow.

**Comment by lovell** [comment]
Brilliant, thank you, I like the `s/library('vips'/static_&/` trick to avoid two (static then shared) meson passes.

I also ended up adding the following when I was looking at this yesterday, which led to me think we should add new booleans to `meson_options.txt` to optionally exclude these subdirs.
```
sed -i'.bak' "/subdir('man')/{N;N;N;N;d;}" meson.build
```
Alternatively, we might be able to avoid it by passing ninja a named target.
```
ninja -C _build cplusplus/libvips-cpp.so.42.15.0
```

**Comment by kleisauke** [comment]
Commit https://github.com/kleisauke/libvips-packaging/commit/8a48dd05f8d5425c332907a96f78da3c5df601bf fixes the previous implementation by not hiding all the symbols from `libgobject-2.0.a` (the FFI bindings also require symbols from this library).

I also managed to fix the rpath issue with that commit, it seems that the `-Dcpp_link_args=` argument would override the `LDFLAGS` environment variable. This also makes link-time garbage collection effective, the library size is now reduced by ~1.8 MB.

A few new options to `meson_options.txt` to optionally exclude those subdirs would indeed be useful to have. The named target trick is also a way to resolve that, but it needs to be changed for each major/minor/patch release of libvips.

**Comment by kleisauke** [comment]
> Make libaom a non-private dependency of libheif, since Meson doesn't respect the `PKG_CONFIG="pkg-config --static"` env to force outputting linker flags for static linking.

Any binaries specified in the Meson cross-file would override this environment variable. This has been fixed with commit 
https://github.com/kleisauke/libvips-packaging/commit/3dd029ba318ec5b2185e0abce336857f9ddf40db instead.

**Comment by lovell** [comment]
Are we ready to test this out with v8.13.0-rc1?

**Comment by kleisauke** [comment]
I just opened PR https://github.com/lovell/sharp-libvips/pull/144 for this.
