### ISSUE TITLE
libpoppler addition

### ISSUE THREAD

**Issue by ramiel** [lovell/sharp-libvips#20]
Since libvips can use libpoppler to open PDF, can it be added to this builds?

**Comment by lovell** [comment]
Hello, libpoppler is licenced under the GPL rather than e.g. the shared-library friendly LGPL.

Including a GPL shared library would mean any code using sharp inside the same `node` process would also then become GPL.

Excluding GPL libraries from the pre-built binaries prevents anyone being accidentally exposed to possible licensing problems.

sharp will always look for and use a globally-installed copy of libvips so you're free to compile it with the dependencies you need and therefore the licensing terms you're willing to accept.

**Comment by ramiel** [comment]
Yes, the license issue is important. I will compile the library on my own. Thank you for your time.

**Comment by ramiel** [comment]
Can you give me some hint how to modify this project to use poppler or pdfium? If you have time, otherwise ignore me.

**Comment by lovell** [comment]
Please see https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball for more information about compiling libvips from source with support for dependencies such as libpoppler.
