### ISSUE TITLE
Linux: investigate `execstack -c` with shared libraries

### ISSUE THREAD

**Issue by lovell** [lovell/sharp-libvips#3]
See https://github.com/lovell/sharp/issues/1108

**Comment by bogdan-calapod** [comment]
Replying here instead of the previous issue (to not open it again) - I've tried running ` execstack -c node_modules/sharp/vendor/lib/librsvg-2.so.2` before executing the script that imports `sharp` and it does indeed seem to work.

Would it be feasible to detect a WSL environment and either execute or prompt the user to execute the line above ?

**Comment by lovell** [comment]
Thanks for confirming. The [Linux build script](https://github.com/lovell/sharp-libvips/blob/master/build/lin.sh) can now be modified to do this for all shared libraries. The next major version of sharp will pick up this fix.
