### ISSUE TITLE
Experiment: provide libvips as a single shared library with its dependencies statically-linked 

### ISSUE THREAD

**Issue by lovell** [lovell/sharp-libvips#39]
It looks like macOS doesn't expand `@loader_path` to the actual filesystem path before checking if the rpath of a dylib file has already been loaded. This means that different versions of sharp at different filesystem locations loaded in the same process can conflict when an earlier version is loaded before a later version.

To attempt to deal with this, we can experiment with unpacking prebuilt libvips binaries into versioned directory under `vendor`, e.g. `node_modules/sharp/vendor/8.9.0/lib/...`, which should then ensure the rpath includes the version number.

**Comment by kleisauke** [comment]
Sorry for the delay, I was a bit busy with several projects.

Here are the relevant changes that provides libvips as a single shared library with its dependencies statically-linked:
https://github.com/lovell/sharp/compare/master...kleisauke:statically-linked
https://github.com/lovell/sharp-libvips/compare/master...kleisauke:sharp-static
https://github.com/lovell/package-libvips-darwin/compare/master...kleisauke:sharp-static

The prebuilt libvips binaries can be found here:
https://github.com/kleisauke/libvips-packaging/releases/tag/v8.9.1-sharp-static

Any help with testing would be much appreciated, testing can be done with:
```bash
npm install kleisauke/sharp#statically-linked
```

TODO: 
- The Windows builds still packages `libgobject-2.0-0.dll` and `libglib-2.0-0.dll`, could we also statically-link these dependencies?
  - The FFI-based bindings still need these DLLs[<sup>1</sup>](https://github.com/libvips/pyvips/blob/3bc8e84bd748e284b0ba3f5c29b297b212528800/pyvips/__init__.py#L56-L59)[<sup>2</sup>](https://github.com/libvips/ruby-vips/blob/03ebf0987dd9822cd81c7eccb9b73f974d84da5c/lib/vips.rb#L45)[<sup>3</sup>](https://github.com/libvips/ruby-vips/blob/03ebf0987dd9822cd81c7eccb9b73f974d84da5c/lib/vips.rb#L137)[<sup>4</sup>](https://github.com/kleisauke/net-vips/blob/0750347979478726faa3ae65c6ea3081b3f5a227/src/NetVips/Interop/Libraries.Windows.cs#L5-L6).
  - Probably we should wait for [GNOME/glib#1316](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1316) when we're considering this.
- How should we release the [`-static` Windows builds](https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.1-static)? We could:
  1. separate the release (i.e. `v8.9.1-static`);
  2. just provide the `-static` builds in the same release;
  3. swap the shared builds (i.e. `vips-dev-w64-web-x.y.z.zip` and `vips-dev-w32-web-x.y.z.zip`) with the static builds (this reduces the overall build time).
- Investigate static linking on macOS (see https://github.com/kleisauke/libvips-packaging/issues/1).
- ARM binaries are now built with full optimization (`-O3`) instead of size optimization (`-Os`). Could this cause any side effects?

> I've just re-read what you wrote and I might have originally misunderstood. Are you suggesting we link libvips with its dependencies statically and bundle them all into one big shared library file, that is then dynamically linked with `sharp.node` (which is then dynamically linked to `node` itself)? If so, that definitely makes sense and is worth continuing with, especially as licensing would remain pretty much as-is.

Yeah, that's what I meant. Not sure how this is called (a "_pseudo-static_" / "_semi-static_" library?). Anyways, this will solve most dependencies issues. 

> This means that different versions of sharp at different filesystem locations loaded in the same process can conflict when an earlier version is loaded before a later version.

This issue is a bit trickier to solve. I guess it could be resolved by ensuring that all sharp versions are the same version within the `package.json`. yarn has an easy way of doing this:
```json
  "resolutions": {
    "sharp": "0.25.2"
  }
```
An alternative way for Linux would be to bump the soname of libvips (and the C++ binding) for each release to ensure the dynamic linker will load the latest ABI-compatible version. For macOS this is resolved by modifying the "install name" to include the versioned subdirectory. AFAIK Windows doesn't have this issue.

**Comment by lovell** [comment]
Brilliant, thank you for all your work on this Kleis, I'll make some time during the next week to start to test this.

I agree with moving the macOS build from being homebrew-based to something more like the Linux approach. I don't have a macOS machine to hand at the moment so will rely heavily on CI tooling for this.

For Windows I think I prefer your option ii of providing both static and non-static alongside each other. Hopefully we can rely on CI to run these in parallel.

Runtime linking with the wrong version of glib has been a problem for sharp users so for non-sharp FFI users perhaps we need a third, -ffi-static variant, where only the DLLs it needs remain shared.

The use of the `-Os` flag with ARM was due to smaller binaries being more performant when I tested on ARMv6 machines a few years ago. Newer 64-bit chips support much larger CPU caches (e.g. ARMv8 L2 is 4MB vs ARMv6's 128KB) and will benefit from `-O3` more, so I don't see this being a problem.

**Comment by janakg** [comment]
@lovell, this is the best approach. We can test on a mac machine, do you need any help get this moving?

**Comment by kleisauke** [comment]
Thanks for incorporating the script improvements into master! I've merged it back into [`sharp-static`](https://github.com/kleisauke/libvips-packaging/tree/sharp-static) for easier reviewing: https://github.com/lovell/sharp-libvips/compare/master...kleisauke:sharp-static

The changes are now minimal, it mostly swaps ` --enable-shared --disable-static` with `--enable-static --disable-shared`. If you want, I could make a PR.

Also, should I undo the `SONAME` change for Linux? I don't think it's relevant to this issue.

> I agree with moving the macOS build from being homebrew-based to something more like the Linux approach. I don't have a macOS machine to hand at the moment so will rely heavily on CI tooling for this.

Unfortunately, I don't have access to a macOS machine either. Perhaps we could also look to MacPorts? I'm not sure if they distribute pre-built static binaries.

> For Windows I think I prefer your option ii of providing both static and non-static alongside each other. Hopefully we can rely on CI to run these in parallel.

I now distribute the `-static` variant within the [build-win64-mxe releases](https://github.com/libvips/build-win64-mxe/releases). Indeed, hopefully we can rely on CI to build these binaires. I tried this in the past (see for e.g. this [Travis configuration](https://github.com/libvips/build-win64-mxe/blob/79250e3f0d34d4a774859d6f912441d779aecc2b/.travis.yml)), but I've disabled it for now because the pre-built packages available on `pkg.mxe.cc` are out-of-sync (it's necessary for GCC, which can easily time-out if it's built on Travis).

> Runtime linking with the wrong version of glib has been a problem for sharp users so for non-sharp FFI users perhaps we need a third, -ffi-static variant, where only the DLLs it needs remain shared.

Issue [GNOME/glib#692](https://gitlab.gnome.org/GNOME/glib/issues/692) is blocking this, but I might be able to test some patches listed there.

> The use of the `-Os` flag with ARM was due to smaller binaries being more performant when I tested on ARMv6 machines a few years ago. Newer 64-bit chips support much larger CPU caches (e.g. ARMv8 L2 is 4MB vs ARMv6's 128KB) and will benefit from `-O3` more, so I don't see this being a problem.

I thought it wouldn't be a problem either, thanks for checking.

**Comment by lovell** [comment]
@kleisauke Thanks, I hadn't quite finished comprehending/synchronising everything when I pushed last night, but have now.

I had to clear CFLAGS when cross-compiling with meson as otherwise it erroneously tries to compile a test program for the build machine but using the host flags. I also had to pin meson to 0.53.2 as there were other cross-compilation problems that I've not fully investigated yet.

As you suggest, I think we can put the SONAME changes to the side for now.

Lets focus on Linux and Windows for now, then we can revisit the macOS tarballs later.

Happy for a PR to update from shared to static.

Thanks for all your help with this so far!

**Comment by kleisauke** [comment]
After 48 attempts, I managed to make the packaging script compatible with macOS, see commit:
https://github.com/kleisauke/libvips-packaging/commit/4f27c9a5cddbee1146f4a7ac74db1594b5b12623

It now run successfully on a macOS container provided by GitHub Actions! See:
https://github.com/kleisauke/libvips-packaging/runs/690315764
https://travis-ci.org/github/kleisauke/sharp/builds/688949925
https://github.com/kleisauke/libvips-packaging/releases/tag/v8.9.2-sharp-static

You can expect a PR somewhere this week. Do you prefer that I squash and rebase all commits?

**Comment by lovell** [comment]
This is amazing, thank you Kleis, a (squashed+rebased) PR would be very welcome!

**Comment by janakg** [comment]
Even with this change, Electron fails to load the GUI in Ubuntu 20.04 and 18.04. Is it because of gtk deps of sharp? please let me know if there is a way to work around this.

1. Electron: 8.5.5
2. Sharp: 0.26.3
3. Ubuntu: 20.04

**Comment by lovell** [comment]
@janakg Please see https://github.com/lovell/sharp/issues/2356
